### ISSUE TITLE
upgrade panel bug

### ISSUE THREAD

**Issue by LilSadPanda** [Revenact/Pterodactyl-Script#37]
**Note: for support questions, please use the [Discord](https://revenact.io/discord)**. This repository's issues are reserved for feature requests and bug reports.

* **I'm submitting a ...**
  - [ *] Bug Report
  - [ ] Feature Request
  - [ ] Support Request => Please do not submit support request here, see note at the top of this template.

* **Do you want to request a *feature* or report a *bug*?**
Bug

* **[Pastebin](https://pastebin.com) link of the error**
NO error

* **What is the expected behavior?**
Update script does not work upgrading a 1.x panel to the latest version.

* **What is the motivation / use case for changing the behavieverything seems to be working within th panel but once you go check the panel version its still the old version.

* **Please tell us about your environment:**

```
  - Version: v0.0.8
  - OS: Ubuntu 20.04
  - Install Options: Nginx
```

* **Other information** (e.g. detailed explanation, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, gitter, etc)

**Comment by tommytran732** [comment]
Oh, it is because the script was coded for an older version. Next time, if I haven't updated the script yet, just change these variables in here and the upgrades should work fine for 1.0.x versions
![image](https://user-images.githubusercontent.com/57488583/111019255-02c42080-838c-11eb-8ddb-46559d68fb3e.png)
